services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25573:25565"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      ONLINE_MODE: "FALSE"
      VERSION: "1.19.4"
      ALLOW_FLIGHT: "TRUE"
      PAPER_JAR: paper-1.19.4-550.jar
      MAX_MEMORY: 8G
      INIT_MEMORY: 8G
      VIEW_DISTANCE: "1"
      ENTITY_BROADCAST_RANGE_PERCENTAGE: "50"
      ENFORCE_SECURE_PROFILE: "FALSE"
      OPS: |
        bot
        username1
        username2
    volumes:
      - ~/MINECRAFTEXPERIMENTS/AgenticMinecraft/server-setup/data:/data
      - ~/MINECRAFTEXPERIMENTS/AgenticMinecraft/server-setup/mods:/data/mods
      - ~/MINECRAFTEXPERIMENTS/AgenticMinecraft/server-setup/server:/server
